language: python

python:
  - "3.4"
  - "2.7"
  - "pypy"

env:
  - "$DJANGO='django<1.9'"

sudo: false

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install $DJANGO
  - pip install -r requirements-dev.txt
  - pip install coveralls
  - pip freeze

# command to run tests, e.g. python setup.py test
script: make check

after_success: coveralls
